const fs = require("fs")
const { join } = require("path")

const languages = fs.readdirSync(join(__dirname, "db", "stopwords"))

let js = "/* Auto-generated by build-index.js */module.exports = {};"

languages.forEach(language => {
    let stopWords = fs.readFileSync(join(__dirname, "db", "stopwords", language), "utf-8").split("\n")
    // Cleanup
    stopWords = stopWords.filter(s => s)
    js += `module.exports.${language}=${JSON.stringify(stopWords)};`
})

fs.writeFileSync("index.js", js)

console.log(`Built ${js.length} bytes`)